package com.example.myapplication;

import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.SearchView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ManuallySelect extends AppCompatActivity {

    private ListView listView;
    private SearchView searchView;
    private ArrayAdapter<String> adapter;
    private List<String> dataList;
    private List<Boolean> checkedItems;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.select_manually);

        listView = findViewById(R.id.listView);
        searchView = findViewById(R.id.searchView);

        // Initialize the data source
        dataList = Arrays.asList(
                "Salt",
                "Sugar",
                "Water",
                "Garlic",
                "Onion",
                "Black Pepper",
                "Olive Oil",
                "Vegetable Oil",
                "Butter",
                "Lemon Juice",
                "Vinegar",
                "Cinnamon",
                "Cumin",
                "Paprika",
                "Chili Powder",
                "Thyme",
                "Rosemary",
                "Basil",
                "Oregano",
                "Parsley",
                "Cilantro",
                "Mint",
                "Ginger",
                "Nutmeg",
                "Vanilla Extract",
                "Honey",
                "Maple Syrup",
                "Parmesan Cheese",
                "Cheddar Cheese",
                "Mozzarella Cheese",
                "Goat Cheese",
                "Feta Cheese",
                "Blue Cheese",
                "Swiss Cheese",
                "Provolone Cheese",
                "Monterey Jack Cheese",
                "Cream Cheese",
                "Sour Cream",
                "Yogurt",
                "Cottage Cheese",
                "Heavy Cream",
                "Whipped Cream",
                "Egg",
                "Milk",
                "Flour",
                "Soy Sauce",
                "Tomato Sauce",
                "Ketchup",
                "Mayonnaise",
                "Mustard",
                "Hot Sauce",
                "BBQ Sauce",
                "Salsa",
                "Peanut Butter",
                "Almond Butter",
                "Cashew Butter",
                "Sunflower Butter",
                "Nutella",
                "Jelly",
                "Jam",
                "Chocolate",
                "White Chocolate",
                "Dark Chocolate",
                "Milk Chocolate",
                "Cocoa Powder",
                "Coconut Milk",
                "Coconut Cream",
                "Coconut Oil",
                "Coconut Flakes",
                "Coconut Water",
                "Rice",
                "Pasta",
                "Bread",
                "Tortillas",
                "Pita Bread",
                "Baguette",
                "Croissant",
                "Rolls",
                "Bagels",
                "Pancake Mix",
                "Cereal",
                "Granola",
                "Oatmeal",
                "Corn Flakes",
                "Raisins",
                "Dried Cranberries",
                "Dried Apricots",
                "Dried Figs",
                "Dates",
                "Peanuts",
                "Almonds",
                "Cashews",
                "Pistachios",
                "Hazelnuts",
                "Macadamia Nuts",
                "Walnuts",
                "Pecans",
                "Sunflower Seeds",
                "Pumpkin Seeds",
                "Chia Seeds",
                "Flaxseeds",
                "Hemp Seeds",
                "Poppy Seeds",
                "Quinoa",
                "Brown Rice",
                "Wild Rice",
                "Barley",
                "Oats",
                "Couscous",
                "Bulgur",
                "Lentils",
                "Chickpeas",
                "Black Beans",
                "Pinto Beans",
                "Kidney Beans",
                "Lima Beans",
                "Green Beans",
                "Peas",
                "Corn",
                "Carrots",
                "Celery",
                "Onions",
                "Garlic",
                "Potatoes",
                "Sweet Potatoes",
                "Spinach",
                "Kale",
                "Lettuce",
                "Cabbage",
                "Broccoli",
                "Cauliflower",
                "Tomatoes",
                "Cucumbers",
                "Zucchini",
                "Mushrooms",
                "Radishes",
                "Beets",
                "Bell Peppers",
                "Chili Peppers",
                "Jalapenos",
                "Habanero Peppers",
                "Eggplant",
                "Asparagus",
                "Artichokes",
                "Avocado",
                "Strawberries",
                "Blueberries",
                "Raspberries",
                "Blackberries",
                "Cranberries",
                "Apples",
                "Oranges",
                "Grapes",
                "Pineapple",
                "Mangoes",
                "Bananas",
                "Lemons",
                "Limes",
                "Peaches",
                "Plums",
                "Pears",
                "Watermelon",
                "Honeydew Melon",
                "Cantaloupe",
                "Kiwi",
                "Passion Fruit",
                "Dragon Fruit",
                "Pomegranate",
                "Guava",
                "Coconut",
                "Mint Leaves",
                "Parsley",
                "Cilantro",
                "Basil Leaves",
                "Rosemary",
                "Thyme",
                "Dill",
                "Bay Leaves",
                "Sage",
                "Tarragon",
                "Marjoram",
                "Oregano",
                "Chives",
                "Scallions",
                "Green Onions",
                "Red Onions",
                "Shallots",
                "Ginger",
                "Turmeric",
                "Cayenne Pepper",
                "Paprika",
                "Cinnamon",
                "Nutmeg",
                "Cloves",
                "Allspice",
                "Cardamom",
                "Vanilla Extract",
                "Almond Extract",
                "Lemon Zest",
                "Lime Zest",
                "Orange Zest",
                "Brown Sugar",
                "Powdered Sugar",
                "Granulated Sugar",
                "White Sugar",
                "Honey",
                "Maple Syrup",
                "Corn Syrup",
                "Agave Nectar",
                "Molasses",
                "Stevia",
                "Xylitol",
                "Coconut Sugar",
                "Artificial Sweeteners",
                "Salt",
                "Black Pepper",
                "Cayenne Pepper",
                "Paprika",
                "Garlic Powder",
                "Onion Powder",
                "Cumin",
                "Cinnamon",
                "Nutmeg",
                "Turmeric",
                "Chili Powder",
                "Oregano",
                "Thyme",
                "Rosemary",
                "Basil",
                "Parsley",
                "Cilantro",
                "Bay Leaves",
                "Dill",
                "Ginger",
                "Allspice",
                "Cardamom",
                "Cloves",
                "Mustard Powder",
                "Coriander",
                "Fennel Seeds",
                "Caraway Seeds",
                "Poppy Seeds",
                "Sesame Seeds",
                "Sunflower Seeds",
                "Pumpkin Seeds",
                "Flaxseeds",
                "Chia Seeds",
                "Hemp Seeds",
                "Peppercorns",
                "Vanilla Beans",
                "Lemon Zest",
                "Lime Zest",
                "Orange Zest",
                "Coconut Flakes",
                "Almonds",
                "Cashews",
                "Pistachios",
                "Hazelnuts",
                "Macadamia Nuts",
                "Walnuts",
                "Pecans",
                "Brazil Nuts",
                "Chestnuts",
                "Peanuts",
                "Flour",
                "Sugar",
                "Baking Powder",
                "Baking Soda",
                "Yeast",
                "Salt",
                "Butter",
                "Eggs",
                "Milk",
                "Cream",
                "Sour Cream",
                "Yogurt",
                "Cheese",
                "Oil",
                "Vanilla Extract",
                "Lemon Juice",
                "Lime Juice",
                "Orange Juice",
                "Cocoa Powder",
                "Chocolate Chips",
                "Coconut Flakes",
                "Raisins",
                "Dried Cranberries",
                "Dried Apricots",
                "Dried Figs",
                "Dates",
                "Bananas",
                "Applesauce",
                "Pumpkin Puree",
                "Sweet Potato Puree",
                "Strawberry Jam",
                "Raspberry Jam",
                "Blueberry Jam",
                "Peanut Butter",
                "Almond Butter",
                "Cashew Butter",
                "Honey",
                "Maple Syrup",
                "Corn Syrup",
                "Molasses",
                "Stevia",
                "Agave Nectar",
                "Powdered Sugar",
                "Brown Sugar",
                "Granulated Sugar",
                "White Sugar",
                "Brown Rice Syrup",
                "Coconut Sugar",
                "Artificial Sweeteners",
                "Cinnamon",
                "Cocoa Powder",
                "Vanilla Extract",
                "Almond Extract",
                "Peppermint Extract",
                "Lemon Zest",
                "Lime Zest",
                "Orange Zest",
                "Coconut Flakes",
                "Almonds",
                "Cashews",
                "Pistachios",
                "Hazelnuts",
                "Macadamia Nuts",
                "Walnuts",
                "Pecans",
                "Brazil Nuts",
                "Chestnuts",
                "Peanuts",
                "Flour",
                "Sugar",
                "Baking Powder",
                "Baking Soda",
                "Yeast",
                "Salt",
                "Butter",
                "Eggs",
                "Milk",
                "Cream",
                "Sour Cream",
                "Yogurt",
                "Cheese",
                "Oil",
                "Vanilla Extract",
                "Lemon Juice",
                "Lime Juice",
                "Orange Juice",
                "Cocoa Powder",
                "Chocolate Chips",
                "Coconut Flakes",
                "Raisins",
                "Dried Cranberries",
                "Dried Apricots",
                "Dried Figs",
                "Dates",
                "Bananas",
                "Applesauce",
                "Pumpkin Puree",
                "Sweet Potato Puree",
                "Strawberry Jam",
                "Raspberry Jam",
                "Blueberry Jam",
                "Peanut Butter",
                "Almond Butter",
                "Cashew Butter",
                "Honey",
                "Maple Syrup",
                "Corn Syrup",
                "Molasses",
                "Stevia",
                "Agave Nectar",
                "Powdered Sugar",
                "Brown Sugar",
                "Granulated Sugar",
                "White Sugar",
                "Brown Rice Syrup",
                "Coconut Sugar",
                "Artificial Sweeteners",
                "Cinnamon",
                "Cocoa Powder",
                "Vanilla Extract",
                "Almond Extract",
                "Peppermint Extract",
                "Lemon Zest",
                "Lime Zest",
                "Orange Zest",
                "Coconut Flakes",
                "Almonds",
                "Cashews",
                "Pistachios",
                "Hazelnuts",
                "Macadamia Nuts",
                "Walnuts",
                "Pecans",
                "Brazil Nuts",
                "Chestnuts",
                "Peanuts",
                "Flour",
                "Sugar",
                "Baking Powder",
                "Baking Soda",
                "Yeast",
                "Salt",
                "Butter",
                "Eggs",
                "Milk",
                "Cream",
                "Sour Cream",
                "Yogurt",
                "Cheese",
                "Oil",
                "Vanilla Extract",
                "Lemon Juice",
                "Lime Juice",
                "Orange Juice",
                "Cocoa Powder",
                "Chocolate Chips",
                "Coconut Flakes",
                "Raisins",
                "Dried Cranberries",
                "Dried Apricots",
                "Dried Figs",
                "Dates",
                "Bananas",
                "Applesauce",
                "Pumpkin Puree",
                "Sweet Potato Puree",
                "Strawberry Jam",
                "Raspberry Jam",
                "Blueberry Jam",
                "Peanut Butter",
                "Almond Butter",
                "Cashew Butter",
                "Honey",
                "Maple Syrup",
                "Corn Syrup",
                "Molasses",
                "Stevia",
                "Agave Nectar",
                "Powdered Sugar",
                "Brown Sugar",
                "Granulated Sugar",
                "White Sugar",
                "Brown Rice Syrup",
                "Coconut Sugar",
                "Artificial Sweeteners",
                "Salt",
                "Pepper",
                "Garlic",
                "Onion",
                "Olive Oil",
                "Vegetable Oil",
                "Canola Oil",
                "Coconut Oil",
                "Sesame Oil",
                "Sunflower Oil",
                "Peanut Oil",
                "Butter",
                "Cheese",
                "Milk",
                "Eggs",
                "Soy Sauce",
                "Ketchup",
                "Mayonnaise",
                "Mustard",
                "Hot Sauce",
                "BBQ Sauce",
                "Salsa",
                "Peanut Butter",
                "Almond Butter",
                "Cashew Butter",
                "Nutella",
                "Jelly",
                "Jam",
                "Chocolate",
                "White Chocolate",
                "Dark Chocolate",
                "Milk Chocolate",
                "Cocoa Powder",
                "Coconut Milk",
                "Coconut Cream",
                "Coconut Oil",
                "Coconut Flakes",
                "Coconut Water",
                "Rice",
                "Pasta",
                "Bread",
                "Tortillas",
                "Pita Bread",
                "Baguette",
                "Croissant",
                "Rolls",
                "Bagels",
                "Pancake Mix",
                "Cereal",
                "Granola",
                "Oatmeal",
                "Corn Flakes",
                "Raisins",
                "Dried Cranberries",
                "Dried Apricots",
                "Dried Figs",
                "Dates",
                "Peanuts",
                "Almonds",
                "Cashews",
                "Pistachios",
                "Hazelnuts",
                "Macadamia Nuts",
                "Walnuts",
                "Pecans",
                "Sunflower Seeds",
                "Pumpkin Seeds",
                "Peanuts",
                "Tree Nuts",
                "Milk",
                "Eggs",
                "Wheat",
                "Soy",
                "Fish",
                "Shellfish",
                "Sesame",
                "Mustard",
                "Celery",
                "Sulfites",
                "Lupin",
                "Mollusks",
                "Corn",
                "Gluten",
                "Kiwi",
                "Avocado",
                "Banana",
                "Chocolate",
                "Strawberries",
                "Oranges",
                "Tomatoes",
                "Pineapple",
                "Grapes",
                "Apples",
                "Soybeans",
                "Beef",
                "Pork",
                "Chicken",
                "Turkey",
                "Lamb",
                "Venison",
                "Shrimp",
                "Crab",
                "Lobster",
                "Oysters",
                "Clams",
                "Mussels",
                "Scallops",
                "Squid",
                "Octopus",
                "Anchovies",
                "Salmon",
                "Tuna",
                "Trout",
                "Haddock",
                "Cod",
                "Sardines",
                "Mackerel",
                "Halibut",
                "Sole",
                "Swordfish",
                "Mahi Mahi",
                "Walnuts",
                "Almonds",
                "Cashews",
                "Pecans",
                "Hazelnuts",
                "Macadamia Nuts",
                "Pistachios",
                "Brazil Nuts",
                "Coconut",
                "Cashew",
                "Pine Nuts",
                "Hemp Seeds",
                "Chia Seeds",
                "Flaxseeds",
                "Sunflower Seeds",
                "Poppy Seeds",
                "Pumpkin Seeds",
                "Quinoa",
                "Barley",
                "Rye",
                "Oats",
                "Buckwheat",
                "Sorghum",
                "Millet",
                "Spelt",
                "Triticale",
                "Cornstarch",
                "Cornmeal",
                "Corn Syrup",
                "Soy Sauce",
                "Tamari",
                "Miso",
                "Tempeh",
                "Tofu",
                "Textured Vegetable Protein",
                "Wheat Starch",
                "Wheat Bran",
                "Wheat Germ",
                "Baker's Yeast",
                "Brewer's Yeast",
                "Monosodium Glutamate (MSG)",
                "Caffeine",
                "Red Dye",
                "Yellow Dye",
                "Blue Dye",
                "Sulfur Dioxide",
                "Artificial Sweeteners",
                "Artificial Preservatives",
                "Artificial Flavors",
                "Artificial Colors",
                "Nitrates",
                "Nitrites",
                "Sodium Benzoate",
                "Aspartame",
                "Saccharin",
                "Sucralose",
                "Acesulfame Potassium",
                "Carrageenan"
                // Add more ingredients as needed
        );

        // Initialize the checked items list
        checkedItems = new ArrayList<>();
        for (int i = 0; i < dataList.size(); i++) {
            checkedItems.add(false);
        }

        // Create and set the adapter
        adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_multiple_choice, dataList);
        listView.setAdapter(adapter);
        listView.setChoiceMode(ListView.CHOICE_MODE_MULTIPLE);

        // Set the search view listener
        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                adapter.getFilter().filter(newText);
                return false;
            }
        });

        // Set the list view item click listener
        listView.setOnItemClickListener((parent, view, position, id) -> {
            boolean isChecked = listView.isItemChecked(position);
            checkedItems.set(position, isChecked);
            Toast.makeText(ManuallySelect.this, dataList.get(position) + " - Checked: " + isChecked, Toast.LENGTH_SHORT).show();
        });
    }
}
